dependencies = []
description = "Simple package manager for Luau"
files = ["*"]
keywords = [""]
main = { lib = "./src/api.luau", bin = "./src/init.luau" }
name = "epinephrine"
owner = "plainenglish"
repository = "https://github.com/Spearhead-Industries/epinephrine.git"
version = "0.1.2"

[build_config]
name = "epi"

[build_config.release]
debug_level = 0
optimisation_level = 2
