description = "Simple package manager for Luau"
files = ["*"]
keywords = [""]
name = "epinephrine"
owner = "plainenglish"
repository = "https://github.com/Spearhead-Industries/epinephrine.git"
version = "0.1.3"

[build_config]
name = "epi"

[build_config.release]
debug_level = 0
optimisation_level = 2

[dependencies]

[main]
bin = "./src/init.luau"
lib = "./src/api.luau"
